name: matthewneuman
favicon: null
layout_spectrum: 0.88366
typography_spectrum: 0.76719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bdbdbd'
    - '#9a9a9a'
    - '#424242'
    - '#676767'
  brandStrength: 0.5
  lightness: 0.6307288384996355
  saturation: 0.3125
  rhythmicContrast: 0.25176939321681857
purpose: []
